export const PROVIDERS = [
  {
    id: '1',
    name: 'Laura Gómez',
    initials: 'LG',
    color: '#7c3aed',
    specialty: 'Entrenadora Personal',
    category: 'Fitness',
    rating: 4.9,
    reviews: 87,
    location: 'Chapinero, Bogotá',
    serviceType: 'both',
    address: 'Cra 7 # 45-12',
    lat: 4.6534,
    lng: -74.0628,
    verified: true,
    price: '$80.000/sesión',
    availability: 'Lun–Sáb 6am–8pm',
    about:
      'Entrenadora certificada con 6 años de experiencia en fitness funcional, pérdida de peso y tonificación. Me especializo en entrenamientos personalizados y acompañamiento nutricional básico.',
    tags: ['Funcional', 'Pérdida de peso', 'Tonificación', 'HIIT'],
    whatsapp: '573001234567',
  },
  {
    id: '2',
    name: 'María Fernández',
    initials: 'MF',
    color: '#f472b6',
    specialty: 'Nutricionista',
    category: 'Nutrición',
    rating: 4.8,
    reviews: 63,
    location: 'Usaquén, Bogotá',
    serviceType: 'home',
    address: 'Calle 134 # 7-83',
    lat: 4.6977,
    lng: -74.0318,
    verified: true,
    price: '$120.000/consulta',
    availability: 'Lun–Vie 8am–6pm',
    about:
      'Nutricionista clínica con énfasis en nutrición deportiva y trastornos metabólicos. Ofrezco planes alimenticios personalizados y seguimiento semanal.',
    tags: ['Nutrición deportiva', 'Planes alimenticios', 'Metabolismo'],
    whatsapp: '573009876543',
  },
  {
    id: '3',
    name: 'Valentina Ruiz',
    initials: 'VR',
    color: '#10b981',
    specialty: 'Psicóloga',
    category: 'Psicología',
    rating: 5.0,
    reviews: 41,
    location: 'Laureles, Medellín',
    serviceType: 'online',
    address: 'Virtual / Online',
    lat: 6.2442,
    lng: -75.5731,
    verified: true,
    price: '$150.000/sesión',
    availability: 'Mar–Sáb 9am–7pm',
    about:
      'Psicóloga clínica con enfoque en terapia cognitivo-conductual. Especializada en ansiedad, depresión y bienestar emocional para mujeres.',
    tags: ['TCC', 'Ansiedad', 'Depresión', 'Autoestima'],
    whatsapp: '573005551234',
  },
  {
    id: '4',
    name: 'Camila Torres',
    initials: 'CT',
    color: '#f59e0b',
    specialty: 'Esteticista',
    category: 'Estética',
    rating: 4.7,
    reviews: 109,
    location: 'El Poblado, Medellín',
    serviceType: 'home',
    address: 'Cra 43A # 14-109',
    lat: 6.2078,
    lng: -75.5688,
    verified: true,
    price: '$60.000–$200.000',
    availability: 'Lun–Sáb 8am–7pm',
    about:
      'Esteticista profesional con 8 años de experiencia en tratamientos faciales, masajes relajantes y depilación. Servicio a domicilio en Medellín.',
    tags: ['Facial', 'Masajes', 'Depilación', 'Uñas'],
    whatsapp: '573007778888',
  },
  {
    id: '5',
    name: 'Sofía Morales',
    initials: 'SM',
    color: '#3b82f6',
    specialty: 'Cuidado de niños',
    category: 'Cuidado',
    rating: 4.9,
    reviews: 55,
    location: 'Teusaquillo, Bogotá',
    serviceType: 'home',
    address: 'Calle 38 # 17-52',
    lat: 4.6426,
    lng: -74.0756,
    verified: true,
    price: '$35.000/hora',
    availability: 'Lun–Dom 7am–9pm',
    about:
      'Cuidadora certificada con experiencia en bebés y niños de 0 a 12 años. Ofrezco servicio de niñera, estimulación temprana y apoyo tareas.',
    tags: ['Niñera', 'Bebés', 'Estimulación temprana', 'Tareas'],
    whatsapp: '573003334444',
  },
  {
    id: '6',
    name: 'Diana Vargas',
    initials: 'DV',
    color: '#ec4899',
    specialty: 'Conductora',
    category: 'Transporte',
    rating: 4.8,
    reviews: 230,
    location: 'Barrios Unidos, Bogotá',
    serviceType: 'home',
    address: 'Servicio en toda Bogotá',
    lat: 4.6673,
    lng: -74.0823,
    verified: true,
    price: '$15.000/carrera',
    availability: 'Lun–Dom 5am–11pm',
    about:
      'Conductora profesional con 4 años de experiencia. Servicio seguro, puntual y exclusivo para mujeres y familias en toda Bogotá.',
    tags: ['Transporte', 'Bogotá', 'Seguro', 'Puntual'],
    whatsapp: '573006667777',
  },
]

export const CATEGORIES = [
  { id: 'all', label: 'Todas', color: '#7c3aed' },
  { id: 'Fitness', label: 'Fitness', color: '#7c3aed' },
  { id: 'Nutrición', label: 'Nutrición', color: '#f472b6' },
  { id: 'Psicología', label: 'Psicología', color: '#10b981' },
  { id: 'Estética', label: 'Estética', color: '#f59e0b' },
  { id: 'Cuidado', label: 'Cuidado', color: '#3b82f6' },
  { id: 'Transporte', label: 'Transporte', color: '#ec4899' },
]
